---
title: "Acceso y Uso de Tecnologías de la Información y la Comunicación Barragán"
author: "Barragán"
format: html
editor: visual
---

```{r}
#| include: false
library(tidyverse)
```

```{r}
#| include: false
my_data <- readRDS("/cloud/project/datos-crudos/EPH_usu_hog_tic_t423[1].txt"
```

```{r}
#| include: false
my_data <- readRDS("/cloud/project/datos-crudos/EPH_usu_indiv_tic_t423[1].txt")
```

```{r}
#| include: false
temp_df <- my_data |> 
  select(CODUSU,NRO_HOGAR, AGLOMERADO,POND_TIC,IH_II_01,COMPONENTE,IP_III_04,IP_III_05,IP_III_06)
```

```{r}
#| include: false
temp_df <- temp_df |> 
  mutate (Hogar_vivienda = "CODUSU")
```

```{r}
#| include: false
temp_df <- temp_df |> 
  mutate (Numero_hogar = "NRO_HOGAR")
```

```{r}
#| include: false
temp_df <- temp_df |> 
  mutate (Ponderacion_de_no_respuesta_tic = "POND_TIC")
```

```{r}
#| include: false
temp_df <- temp_df |> 
  mutate (Computadoras = "IH_II_01")
```

```{r}
#| include: false
temp_df <- temp_df |> 
  mutate (Acceso_internet = "IH_II_02")
```

```{r}
#| include: false
temp_df <- temp_df |> 
  mutate (Rol_hogar = "COMPONENTE")
```

```{r}
#| include: false
temp_df <- temp_df |> 
  mutate (Uso_internet = "IP_III_04")
```

```{r}
#| include: false
temp_df <- temp_df |> 
  mutate (Uso_computadora = "IP_III_05")
```

```{r}
#| include: false
temp_df <- temp_df |> 
  mutate (Uso_celular = "IP_III_06")
```

```{r}
temp_df <- my_data |>
  select(AGLOMERADO) |>
  mutate(
    AGLOMERADO = case_when(
      AGLOMERADO == 02 ~ "AMBA",
      AGLOMERADO == 03 ~ "AMBA",
      AGLOMERADO == 04 ~ "LITORAL",
      AGLOMERADO == 05 ~ "LITORAL",
      AGLOMERADO == 06 ~ "LITORAL",
      AGLOMERADO == 07 ~ "LITORAL",
      AGLOMERADO == 08 ~ "LITORAL",
      AGLOMERADO == 09 ~ "PATAGONIA",
      AGLOMERADO == 10 ~ "CUYO",
      AGLOMERADO == 12 ~ "LITORAL",
      AGLOMERADO == 13 ~ "NOROESTE",
      AGLOMERADO == 14 ~ "LITORAL",
      AGLOMERADO == 15 ~ "LITORAL",
      AGLOMERADO == 17 ~ "Está en sucesión",
      AGLOMERADO == 18 ~ "Está en sucesión",
      AGLOMERADO == 19 ~ "Está en sucesión",
      AGLOMERADO == 20 ~ "Está en sucesión",
      AGLOMERADO == 22 ~ "Está en sucesión",
      AGLOMERADO == 23 ~ "Está en sucesión",
      AGLOMERADO == 25 ~ "Está en sucesión",
      AGLOMERADO == 26 ~ "Está en sucesión",
      AGLOMERADO == 27 ~ "Está en sucesión",
      AGLOMERADO == 29 ~ "Está en sucesión",
      AGLOMERADO == 30 ~ "Está en sucesión",
      AGLOMERADO == 31 ~ "Está en sucesión",
      AGLOMERADO == 32 ~ "Está en sucesión",
      AGLOMERADO == 33 ~ "Está en sucesión",
      AGLOMERADO == 34 ~ "Está en sucesión",
      AGLOMERADO == 36 ~ "Está en sucesión",
      AGLOMERADO == 38 ~ "LITORAL",
      AGLOMERADO == 91 ~ "Está en sucesión",
      AGLOMERADO == 93 ~ "Está en sucesión",
      TRUE ~ "No Encontrado"
    )
```
