project:
  type: book

book:
  title: "Análisis del uso del tiempo en Argentina a partir de la Encuesta Nacional sobre el Uso del Tiempo 2021"
  author: "María Acha"
  date: "11/22/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - capitulo1.qmd
    - capitulo2.qmd
    - capitulo3.qmd
    - conclusiones.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



