---
title: "Nota sobre GGplot"
author: "Sasha"
format: html
editor: visual
---

```{r}
#| include: false
library(tidyverse)
my_data <- readr::read_delim(here::here("datos-crudos/enut2021_base.txt"), delim = "|")
source(here::here("R/nombrar-sexo.R"))
knitr::opts_chunk$set(echo=FALSE, message = FALSE)
```


## Plot 

```{r}
#| echo: false
#| message: false
my_data |>
  mutate(sexo = nombrar_sexo(SEXO_SEL)) |>
  select(sexo,EDAD_SEL, TCS_ACT_DORMIR) |>
  group_by(EDAD_SEL, sexo) |>
  summarize(
    Media = mean(TCS_ACT_DORMIR),
    Mediana = median(TCS_ACT_DORMIR),
    Desviacion = sd(TCS_ACT_DORMIR)
  ) |> 
  ggplot(aes(x=EDAD_SEL, y=Media, color = sexo))+
  #geom_col()+
  geom_smooth()+
  scale_x_continuous(breaks = seq(0,100, by =10))+
xlab("Edad")+
  ylab("Tiempo dedicado a dormir (en minutos)")
```

## Plot 2

```{r}
#| label: fig-plot-1
#| fig-cap: "Tiempo dedicado a Dormir de Hombres y Mujeres"
#| fig-subcap: "Medido en minutos"
#| echo: false
my_data |>
  mutate(sexo = nombrar_sexo(SEXO_SEL)) |>
  select(sexo,EDAD_SEL, TCS_ACT_DORMIR) |>
  group_by(EDAD_SEL, sexo) |>
  summarize(
    Media = mean(TCS_ACT_DORMIR),
    Mediana = median(TCS_ACT_DORMIR),
    Desviacion = sd(TCS_ACT_DORMIR)
  ) |> 
  ggplot(aes(x=EDAD_SEL, y=Media, color = sexo))+
  #geom_col()+
  geom_smooth()+
  scale_x_continuous(breaks = seq(0,100, by =10))+
  xlab("Edad")+
  ylab("Tiempo (minutos)")

```

## Plot 3

```{r}
#| label: fig-plot-3
#| fig-cap: "Tiempo dedicado a Dormir de Hombres y Mujeres"
#| fig-subcap: "Medido en minutos"
#| echo: false
my_data |>
  mutate(sexo = nombrar_sexo(SEXO_SEL)) |>
  select(sexo,EDAD_SEL, TCS_ACT_DORMIR) |>
  group_by(EDAD_SEL, sexo) |>
  summarize(
    Media = mean(TCS_ACT_DORMIR),
    Mediana = median(TCS_ACT_DORMIR),
    Desviacion = sd(TCS_ACT_DORMIR)
  ) |> 
  ggplot(aes(x=EDAD_SEL, y=Media, color = sexo))+
  #geom_col()+
  geom_smooth()+
  scale_x_continuous(breaks = seq(0,100, by =10))+
  labs(x="Edad", y="Tiempo", color = "Genero")

```

