---
title: "Exploratorio Subte"
format: html
editor: visual
---

```{r}
my_data <- readr::read_rds(here::here("data/datos-sube.rds"))
```

```{r}
my_data <- my_data %>% 
  mutate(AÑO = lubridate::year(DIA))

my_data %>% filter(AÑO == '2024') %>% head()
```

```{r}
my_data <- my_data %>% 
  filter(!is.na(SUBSIDIO), 
         SUBSIDIO != "OTRO") %>% 
  mutate(MES = lubridate::month(DIA))

my_data %>% head()
```

```{r}
my_summary_by_year <- my_data %>% 
  group_by(AÑO, SUBSIDIO) %>% 
  summarize(
    Pasajes = sum(CANT_TRJ),
    .groups = "drop"
  ) 
```

```{r}
my_summary_by_year <- my_data %>% 
  group_by(AÑO, SUBSIDIO) %>% 
  summarize(
    Pasajes = sum(CANT_TRJ),
    .groups = "drop"
  ) 
```

Como no se ve podemos filtrar:///

```{r}
my_summary_by_year <- my_data %>% 
  group_by(AÑO, SUBSIDIO) %>% 
  summarize(
    Pasajes = sum(CANT_TRJ),
    .groups = "drop"
  ) 
```

```{r}
my_summary_by_year_2 <- my_summary_by_year %>% 
  filter(!is.na(SUBSIDIO), SUBSIDIO != "OTRO")

my_summary_3 <- my_summary_by_year_2 %>% 
  group_by(AÑO) %>% 
  summarize(
    TOTAL = sum(Pasajes)
  ) %>% 
  left_join(my_summary_by_year_2) %>% 
  mutate(Relativo = Pasajes/TOTAL) 


my_summary_3 %>% 
  ggplot(aes(AÑO, Relativo, fill = SUBSIDIO))+
  geom_col()+
  theme(legend.position  = "bottom")
```

```{r}
lubridate::month(my_data$DIA %>% tail(), label = TRUE)

```

```{r}
my_summary_3 %>% 
  ggplot(aes(AÑO, Relativo, color = SUBSIDIO))+
  geom_point()+
  geom_line()+
  theme(legend.position  = "bottom")
  
```

### Uso de "Arrange"

```{r}
 

my_data %>% arrange(desc(DIA_TRANSPORTE))
 


```
