##Procedimiento

```{r}
#| include: false
library(tidyverse)
```

```{r}
#| include: false
library(tidyverse)
source(here::here("R/nombraraglomerado.R"))
my_data <- readr::read_delim(here::here("datos-crudos/EPH_usu_hog_tic_t423[1].txt"))
temp_df<- my_data |>
  mutate(AGLOMERADO = nombrar_aglomerado(AGLOMERADO))|>
  filter(IH_II_01<=2)|>
  filter(IH_II_02<=2)|>
  mutate(Computadoras=ifelse(IH_II_01==1,"Si","No"))|>
  mutate(Acceso_internet=ifelse(IH_II_02    ==1,"Si","No"))
 # mutate(Computadoras = IH_II_01)|>
  #mutate( Acceso_internet = IH_II_02)
```

```{r}
#| include: false
my_data2 <- readr::read_delim(here::here("datos-crudos/EPH_usu_indiv_tic_t423[1].txt"))
temp_df2<- my_data2 |>
  mutate(AGLOMERADO = nombrar_aglomerado(AGLOMERADO))|>
filter(IP_III_04<=2)|>
  filter(IP_III_05<=2)|>
filter(IP_III_06<=2)|>
mutate(Uso_internet=ifelse(IP_III_04==1,"Si","No"))|>
  mutate(Uso_computadora=ifelse(IP_III_05==1,"Si","No"))|>
mutate(Uso_celular=ifelse(IP_III_06==1,"Si","No"))
  #mutate( Uso_internet = IP_III_04)|>
  #mutate( Uso_computadora = IP_III_05)|>
  #mutate(Uso_celular=IP_III_06)

```