project:
  type: book

book:
  title: "Acceso y Uso de Tecnologías de la Información y la Comunicación"
  author: "Belén Barragán"
  date: "9/30/2024"
  chapters:
    - index.qmd
    - 1-Introducción.qmd 
    - 2-Datos.qmd  
    - 3-Variables.qmd
    - 4-Preguntas_de_investigación.qmd
    - 5-Procedimiento.qmd
    - 6-Análisis_descriptivo.qmd
    - 7-Conclusiones.qmd
    - 8-references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



