project:
  type: book

book:
  title: "Acceso y Uso de Tecnologías de la Información y la Comunicación"
  author: "Belén Barragán"
  date: "9/30/2024"
  chapters:
    -1.Introducción.qmd 
    -2.Datos.qmd  
    -3.Variables
    -4.Preguntas de investigación.qmd
    -5.Procedimiento.qmd
    -6.Análisis descriptivo.qmd
    -7.references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



