# Prefacio {.unnumbered}

El siguiente trabajo es un proyecto final para la materia Comunicación y Ciencia de datos 2, dictada por el profesor Aleksander Dietrichson durante el segundo cuatrimestre del ciclo lectivo 2024. Dicho proyecto se dividirá de la siguiente manera. En el capítulo "Introducción", se hará una breve introducción al tema a tratar: los accesos y usos de las nuevas tecnologías de la información y la comunicación. En el capítulo "Datos" se dara cuenta de la base de datos a utilizar para analizar sus datos. En el capítulo "Variables" se presentan las variables de análisis. En el capítulo "Preguntas_ de_ investigación", se presentan las preguntas de investigación que trata de abordar este trabajo. En el capítulo "Procedimiento", se presenta el procedimiento a utilizar para abordar los datos. En el capítulo "Análisis  descriptivo", se realiza un análisis de los datos y variables seleccionadas. En el capítulo "Conclusiones", se presentan las conclusiones de este trabajo final de cursada. Y finalmente, en el capítulo "references", se da cuenta de las referencias utilizadas en este trabajo. 